version: '2'
services:
    klav-app:
        image: registry.gitlab.com/klav/klav-back:snapshot
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://klav-mysql:3306/klav?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    klav-mysql:
        extends:
            file: mysql.yml
            service: klav-mysql
